
import "@/css/globals.css";
import "@/css/style.css";
import "@/css/design_system.css"
import "@/css/navbar.css";
import "@/css/footer.css";
import "@/css/hero.css";
import "@/css/block.css";


export const metadata = {
  title: "Fervor Books",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
